name: shoes_shop
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/favicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik-Bold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf

    - family: Rubik-Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf

    - family: Rubik-SemiBold
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf  
 